# .goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X hexyn-aws/cmd/cli.Version={{.Version}}

archives:
  - formats:
      - tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      hexyn-aws_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  abbrev: -1
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
  groups:
    - title: Features
      regexp: '^feat(\(.*\))??:'
      order: 0
    - title: 'Bug fixes'
      regexp: '^fix(\(.*\))??:'
      order: 1
    - title: 'Refactor'
      regexp: '^refactor(\(.*\))??:'
      order: 2
    - title: Others
      order: 999
