name: Bug Report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: Tell us what you did!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code blocks.
      render: shell
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Go version, Hexyn version, etc.
      placeholder: |
        OS: macOS 14.5
        Go: 1.26.2
        Hexyn: v1.0.0
