// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"hexyn-aws/internal/awsx"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCredentialLoader creates a new instance of MockCredentialLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialLoader {
	mock := &MockCredentialLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCredentialLoader is an autogenerated mock type for the CredentialLoader type
type MockCredentialLoader struct {
	mock.Mock
}

type MockCredentialLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialLoader) EXPECT() *MockCredentialLoader_Expecter {
	return &MockCredentialLoader_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockCredentialLoader
func (_mock *MockCredentialLoader) Load() (awsx.LoadedCredentials, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 awsx.LoadedCredentials
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (awsx.LoadedCredentials, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() awsx.LoadedCredentials); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(awsx.LoadedCredentials)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCredentialLoader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockCredentialLoader_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockCredentialLoader_Expecter) Load() *MockCredentialLoader_Load_Call {
	return &MockCredentialLoader_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockCredentialLoader_Load_Call) Run(run func()) *MockCredentialLoader_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCredentialLoader_Load_Call) Return(loadedCredentials awsx.LoadedCredentials, err error) *MockCredentialLoader_Load_Call {
	_c.Call.Return(loadedCredentials, err)
	return _c
}

func (_c *MockCredentialLoader_Load_Call) RunAndReturn(run func() (awsx.LoadedCredentials, error)) *MockCredentialLoader_Load_Call {
	_c.Call.Return(run)
	return _c
}
