// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/ecs"
	mock "github.com/stretchr/testify/mock"
)

// NewMockECSAPI creates a new instance of MockECSAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockECSAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockECSAPI {
	mock := &MockECSAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockECSAPI is an autogenerated mock type for the ECSAPI type
type MockECSAPI struct {
	mock.Mock
}

type MockECSAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockECSAPI) EXPECT() *MockECSAPI_Expecter {
	return &MockECSAPI_Expecter{mock: &_m.Mock}
}

// DescribeServices provides a mock function for the type MockECSAPI
func (_mock *MockECSAPI) DescribeServices(ctx context.Context, params *ecs.DescribeServicesInput, optFns ...func(*ecs.Options)) (*ecs.DescribeServicesOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DescribeServices")
	}

	var r0 *ecs.DescribeServicesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ecs.DescribeServicesInput, ...func(*ecs.Options)) (*ecs.DescribeServicesOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ecs.DescribeServicesInput, ...func(*ecs.Options)) *ecs.DescribeServicesOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ecs.DescribeServicesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ecs.DescribeServicesInput, ...func(*ecs.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockECSAPI_DescribeServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeServices'
type MockECSAPI_DescribeServices_Call struct {
	*mock.Call
}

// DescribeServices is a helper method to define mock.On call
//   - ctx context.Context
//   - params *ecs.DescribeServicesInput
//   - optFns ...func(*ecs.Options)
func (_e *MockECSAPI_Expecter) DescribeServices(ctx interface{}, params interface{}, optFns ...interface{}) *MockECSAPI_DescribeServices_Call {
	return &MockECSAPI_DescribeServices_Call{Call: _e.mock.On("DescribeServices",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockECSAPI_DescribeServices_Call) Run(run func(ctx context.Context, params *ecs.DescribeServicesInput, optFns ...func(*ecs.Options))) *MockECSAPI_DescribeServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ecs.DescribeServicesInput
		if args[1] != nil {
			arg1 = args[1].(*ecs.DescribeServicesInput)
		}
		var arg2 []func(*ecs.Options)
		var variadicArgs []func(*ecs.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*ecs.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockECSAPI_DescribeServices_Call) Return(describeServicesOutput *ecs.DescribeServicesOutput, err error) *MockECSAPI_DescribeServices_Call {
	_c.Call.Return(describeServicesOutput, err)
	return _c
}

func (_c *MockECSAPI_DescribeServices_Call) RunAndReturn(run func(ctx context.Context, params *ecs.DescribeServicesInput, optFns ...func(*ecs.Options)) (*ecs.DescribeServicesOutput, error)) *MockECSAPI_DescribeServices_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeTaskDefinition provides a mock function for the type MockECSAPI
func (_mock *MockECSAPI) DescribeTaskDefinition(ctx context.Context, params *ecs.DescribeTaskDefinitionInput, optFns ...func(*ecs.Options)) (*ecs.DescribeTaskDefinitionOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DescribeTaskDefinition")
	}

	var r0 *ecs.DescribeTaskDefinitionOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ecs.DescribeTaskDefinitionInput, ...func(*ecs.Options)) (*ecs.DescribeTaskDefinitionOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ecs.DescribeTaskDefinitionInput, ...func(*ecs.Options)) *ecs.DescribeTaskDefinitionOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ecs.DescribeTaskDefinitionOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ecs.DescribeTaskDefinitionInput, ...func(*ecs.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockECSAPI_DescribeTaskDefinition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeTaskDefinition'
type MockECSAPI_DescribeTaskDefinition_Call struct {
	*mock.Call
}

// DescribeTaskDefinition is a helper method to define mock.On call
//   - ctx context.Context
//   - params *ecs.DescribeTaskDefinitionInput
//   - optFns ...func(*ecs.Options)
func (_e *MockECSAPI_Expecter) DescribeTaskDefinition(ctx interface{}, params interface{}, optFns ...interface{}) *MockECSAPI_DescribeTaskDefinition_Call {
	return &MockECSAPI_DescribeTaskDefinition_Call{Call: _e.mock.On("DescribeTaskDefinition",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockECSAPI_DescribeTaskDefinition_Call) Run(run func(ctx context.Context, params *ecs.DescribeTaskDefinitionInput, optFns ...func(*ecs.Options))) *MockECSAPI_DescribeTaskDefinition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ecs.DescribeTaskDefinitionInput
		if args[1] != nil {
			arg1 = args[1].(*ecs.DescribeTaskDefinitionInput)
		}
		var arg2 []func(*ecs.Options)
		var variadicArgs []func(*ecs.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*ecs.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockECSAPI_DescribeTaskDefinition_Call) Return(describeTaskDefinitionOutput *ecs.DescribeTaskDefinitionOutput, err error) *MockECSAPI_DescribeTaskDefinition_Call {
	_c.Call.Return(describeTaskDefinitionOutput, err)
	return _c
}

func (_c *MockECSAPI_DescribeTaskDefinition_Call) RunAndReturn(run func(ctx context.Context, params *ecs.DescribeTaskDefinitionInput, optFns ...func(*ecs.Options)) (*ecs.DescribeTaskDefinitionOutput, error)) *MockECSAPI_DescribeTaskDefinition_Call {
	_c.Call.Return(run)
	return _c
}

// ListClusters provides a mock function for the type MockECSAPI
func (_mock *MockECSAPI) ListClusters(ctx context.Context, params *ecs.ListClustersInput, optFns ...func(*ecs.Options)) (*ecs.ListClustersOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListClusters")
	}

	var r0 *ecs.ListClustersOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ecs.ListClustersInput, ...func(*ecs.Options)) (*ecs.ListClustersOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ecs.ListClustersInput, ...func(*ecs.Options)) *ecs.ListClustersOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ecs.ListClustersOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ecs.ListClustersInput, ...func(*ecs.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockECSAPI_ListClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClusters'
type MockECSAPI_ListClusters_Call struct {
	*mock.Call
}

// ListClusters is a helper method to define mock.On call
//   - ctx context.Context
//   - params *ecs.ListClustersInput
//   - optFns ...func(*ecs.Options)
func (_e *MockECSAPI_Expecter) ListClusters(ctx interface{}, params interface{}, optFns ...interface{}) *MockECSAPI_ListClusters_Call {
	return &MockECSAPI_ListClusters_Call{Call: _e.mock.On("ListClusters",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockECSAPI_ListClusters_Call) Run(run func(ctx context.Context, params *ecs.ListClustersInput, optFns ...func(*ecs.Options))) *MockECSAPI_ListClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ecs.ListClustersInput
		if args[1] != nil {
			arg1 = args[1].(*ecs.ListClustersInput)
		}
		var arg2 []func(*ecs.Options)
		var variadicArgs []func(*ecs.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*ecs.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockECSAPI_ListClusters_Call) Return(listClustersOutput *ecs.ListClustersOutput, err error) *MockECSAPI_ListClusters_Call {
	_c.Call.Return(listClustersOutput, err)
	return _c
}

func (_c *MockECSAPI_ListClusters_Call) RunAndReturn(run func(ctx context.Context, params *ecs.ListClustersInput, optFns ...func(*ecs.Options)) (*ecs.ListClustersOutput, error)) *MockECSAPI_ListClusters_Call {
	_c.Call.Return(run)
	return _c
}

// ListServices provides a mock function for the type MockECSAPI
func (_mock *MockECSAPI) ListServices(ctx context.Context, params *ecs.ListServicesInput, optFns ...func(*ecs.Options)) (*ecs.ListServicesOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListServices")
	}

	var r0 *ecs.ListServicesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ecs.ListServicesInput, ...func(*ecs.Options)) (*ecs.ListServicesOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ecs.ListServicesInput, ...func(*ecs.Options)) *ecs.ListServicesOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ecs.ListServicesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ecs.ListServicesInput, ...func(*ecs.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockECSAPI_ListServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServices'
type MockECSAPI_ListServices_Call struct {
	*mock.Call
}

// ListServices is a helper method to define mock.On call
//   - ctx context.Context
//   - params *ecs.ListServicesInput
//   - optFns ...func(*ecs.Options)
func (_e *MockECSAPI_Expecter) ListServices(ctx interface{}, params interface{}, optFns ...interface{}) *MockECSAPI_ListServices_Call {
	return &MockECSAPI_ListServices_Call{Call: _e.mock.On("ListServices",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockECSAPI_ListServices_Call) Run(run func(ctx context.Context, params *ecs.ListServicesInput, optFns ...func(*ecs.Options))) *MockECSAPI_ListServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ecs.ListServicesInput
		if args[1] != nil {
			arg1 = args[1].(*ecs.ListServicesInput)
		}
		var arg2 []func(*ecs.Options)
		var variadicArgs []func(*ecs.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*ecs.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockECSAPI_ListServices_Call) Return(listServicesOutput *ecs.ListServicesOutput, err error) *MockECSAPI_ListServices_Call {
	_c.Call.Return(listServicesOutput, err)
	return _c
}

func (_c *MockECSAPI_ListServices_Call) RunAndReturn(run func(ctx context.Context, params *ecs.ListServicesInput, optFns ...func(*ecs.Options)) (*ecs.ListServicesOutput, error)) *MockECSAPI_ListServices_Call {
	_c.Call.Return(run)
	return _c
}
