// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/ssm"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSSMAPI creates a new instance of MockSSMAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSSMAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSSMAPI {
	mock := &MockSSMAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSSMAPI is an autogenerated mock type for the SSMAPI type
type MockSSMAPI struct {
	mock.Mock
}

type MockSSMAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSSMAPI) EXPECT() *MockSSMAPI_Expecter {
	return &MockSSMAPI_Expecter{mock: &_m.Mock}
}

// GetParameters provides a mock function for the type MockSSMAPI
func (_mock *MockSSMAPI) GetParameters(ctx context.Context, params *ssm.GetParametersInput, optFns ...func(*ssm.Options)) (*ssm.GetParametersOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetParameters")
	}

	var r0 *ssm.GetParametersOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.GetParametersInput, ...func(*ssm.Options)) (*ssm.GetParametersOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.GetParametersInput, ...func(*ssm.Options)) *ssm.GetParametersOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.GetParametersOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ssm.GetParametersInput, ...func(*ssm.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSSMAPI_GetParameters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParameters'
type MockSSMAPI_GetParameters_Call struct {
	*mock.Call
}

// GetParameters is a helper method to define mock.On call
//   - ctx context.Context
//   - params *ssm.GetParametersInput
//   - optFns ...func(*ssm.Options)
func (_e *MockSSMAPI_Expecter) GetParameters(ctx interface{}, params interface{}, optFns ...interface{}) *MockSSMAPI_GetParameters_Call {
	return &MockSSMAPI_GetParameters_Call{Call: _e.mock.On("GetParameters",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockSSMAPI_GetParameters_Call) Run(run func(ctx context.Context, params *ssm.GetParametersInput, optFns ...func(*ssm.Options))) *MockSSMAPI_GetParameters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ssm.GetParametersInput
		if args[1] != nil {
			arg1 = args[1].(*ssm.GetParametersInput)
		}
		var arg2 []func(*ssm.Options)
		var variadicArgs []func(*ssm.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*ssm.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSSMAPI_GetParameters_Call) Return(getParametersOutput *ssm.GetParametersOutput, err error) *MockSSMAPI_GetParameters_Call {
	_c.Call.Return(getParametersOutput, err)
	return _c
}

func (_c *MockSSMAPI_GetParameters_Call) RunAndReturn(run func(ctx context.Context, params *ssm.GetParametersInput, optFns ...func(*ssm.Options)) (*ssm.GetParametersOutput, error)) *MockSSMAPI_GetParameters_Call {
	_c.Call.Return(run)
	return _c
}

// GetParametersByPath provides a mock function for the type MockSSMAPI
func (_mock *MockSSMAPI) GetParametersByPath(ctx context.Context, params *ssm.GetParametersByPathInput, optFns ...func(*ssm.Options)) (*ssm.GetParametersByPathOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetParametersByPath")
	}

	var r0 *ssm.GetParametersByPathOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.GetParametersByPathInput, ...func(*ssm.Options)) (*ssm.GetParametersByPathOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.GetParametersByPathInput, ...func(*ssm.Options)) *ssm.GetParametersByPathOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.GetParametersByPathOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ssm.GetParametersByPathInput, ...func(*ssm.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSSMAPI_GetParametersByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParametersByPath'
type MockSSMAPI_GetParametersByPath_Call struct {
	*mock.Call
}

// GetParametersByPath is a helper method to define mock.On call
//   - ctx context.Context
//   - params *ssm.GetParametersByPathInput
//   - optFns ...func(*ssm.Options)
func (_e *MockSSMAPI_Expecter) GetParametersByPath(ctx interface{}, params interface{}, optFns ...interface{}) *MockSSMAPI_GetParametersByPath_Call {
	return &MockSSMAPI_GetParametersByPath_Call{Call: _e.mock.On("GetParametersByPath",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockSSMAPI_GetParametersByPath_Call) Run(run func(ctx context.Context, params *ssm.GetParametersByPathInput, optFns ...func(*ssm.Options))) *MockSSMAPI_GetParametersByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ssm.GetParametersByPathInput
		if args[1] != nil {
			arg1 = args[1].(*ssm.GetParametersByPathInput)
		}
		var arg2 []func(*ssm.Options)
		var variadicArgs []func(*ssm.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*ssm.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSSMAPI_GetParametersByPath_Call) Return(getParametersByPathOutput *ssm.GetParametersByPathOutput, err error) *MockSSMAPI_GetParametersByPath_Call {
	_c.Call.Return(getParametersByPathOutput, err)
	return _c
}

func (_c *MockSSMAPI_GetParametersByPath_Call) RunAndReturn(run func(ctx context.Context, params *ssm.GetParametersByPathInput, optFns ...func(*ssm.Options)) (*ssm.GetParametersByPathOutput, error)) *MockSSMAPI_GetParametersByPath_Call {
	_c.Call.Return(run)
	return _c
}

// PutParameter provides a mock function for the type MockSSMAPI
func (_mock *MockSSMAPI) PutParameter(ctx context.Context, params *ssm.PutParameterInput, optFns ...func(*ssm.Options)) (*ssm.PutParameterOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PutParameter")
	}

	var r0 *ssm.PutParameterOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.PutParameterInput, ...func(*ssm.Options)) (*ssm.PutParameterOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.PutParameterInput, ...func(*ssm.Options)) *ssm.PutParameterOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.PutParameterOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ssm.PutParameterInput, ...func(*ssm.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSSMAPI_PutParameter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutParameter'
type MockSSMAPI_PutParameter_Call struct {
	*mock.Call
}

// PutParameter is a helper method to define mock.On call
//   - ctx context.Context
//   - params *ssm.PutParameterInput
//   - optFns ...func(*ssm.Options)
func (_e *MockSSMAPI_Expecter) PutParameter(ctx interface{}, params interface{}, optFns ...interface{}) *MockSSMAPI_PutParameter_Call {
	return &MockSSMAPI_PutParameter_Call{Call: _e.mock.On("PutParameter",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockSSMAPI_PutParameter_Call) Run(run func(ctx context.Context, params *ssm.PutParameterInput, optFns ...func(*ssm.Options))) *MockSSMAPI_PutParameter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ssm.PutParameterInput
		if args[1] != nil {
			arg1 = args[1].(*ssm.PutParameterInput)
		}
		var arg2 []func(*ssm.Options)
		var variadicArgs []func(*ssm.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*ssm.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSSMAPI_PutParameter_Call) Return(putParameterOutput *ssm.PutParameterOutput, err error) *MockSSMAPI_PutParameter_Call {
	_c.Call.Return(putParameterOutput, err)
	return _c
}

func (_c *MockSSMAPI_PutParameter_Call) RunAndReturn(run func(ctx context.Context, params *ssm.PutParameterInput, optFns ...func(*ssm.Options)) (*ssm.PutParameterOutput, error)) *MockSSMAPI_PutParameter_Call {
	_c.Call.Return(run)
	return _c
}
