// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"hexyn-aws/internal/secrets"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAWS creates a new instance of MockAWS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAWS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAWS {
	mock := &MockAWS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAWS is an autogenerated mock type for the AWS type
type MockAWS struct {
	mock.Mock
}

type MockAWS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAWS) EXPECT() *MockAWS_Expecter {
	return &MockAWS_Expecter{mock: &_m.Mock}
}

// ECS provides a mock function for the type MockAWS
func (_mock *MockAWS) ECS(ctx context.Context, region string) (secrets.ECSClient, error) {
	ret := _mock.Called(ctx, region)

	if len(ret) == 0 {
		panic("no return value specified for ECS")
	}

	var r0 secrets.ECSClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (secrets.ECSClient, error)); ok {
		return returnFunc(ctx, region)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) secrets.ECSClient); ok {
		r0 = returnFunc(ctx, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(secrets.ECSClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, region)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAWS_ECS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ECS'
type MockAWS_ECS_Call struct {
	*mock.Call
}

// ECS is a helper method to define mock.On call
//   - ctx context.Context
//   - region string
func (_e *MockAWS_Expecter) ECS(ctx interface{}, region interface{}) *MockAWS_ECS_Call {
	return &MockAWS_ECS_Call{Call: _e.mock.On("ECS", ctx, region)}
}

func (_c *MockAWS_ECS_Call) Run(run func(ctx context.Context, region string)) *MockAWS_ECS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAWS_ECS_Call) Return(eCSClient secrets.ECSClient, err error) *MockAWS_ECS_Call {
	_c.Call.Return(eCSClient, err)
	return _c
}

func (_c *MockAWS_ECS_Call) RunAndReturn(run func(ctx context.Context, region string) (secrets.ECSClient, error)) *MockAWS_ECS_Call {
	_c.Call.Return(run)
	return _c
}

// SSM provides a mock function for the type MockAWS
func (_mock *MockAWS) SSM(ctx context.Context, region string) (secrets.SSMClient, error) {
	ret := _mock.Called(ctx, region)

	if len(ret) == 0 {
		panic("no return value specified for SSM")
	}

	var r0 secrets.SSMClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (secrets.SSMClient, error)); ok {
		return returnFunc(ctx, region)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) secrets.SSMClient); ok {
		r0 = returnFunc(ctx, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(secrets.SSMClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, region)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAWS_SSM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SSM'
type MockAWS_SSM_Call struct {
	*mock.Call
}

// SSM is a helper method to define mock.On call
//   - ctx context.Context
//   - region string
func (_e *MockAWS_Expecter) SSM(ctx interface{}, region interface{}) *MockAWS_SSM_Call {
	return &MockAWS_SSM_Call{Call: _e.mock.On("SSM", ctx, region)}
}

func (_c *MockAWS_SSM_Call) Run(run func(ctx context.Context, region string)) *MockAWS_SSM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAWS_SSM_Call) Return(sSMClient secrets.SSMClient, err error) *MockAWS_SSM_Call {
	_c.Call.Return(sSMClient, err)
	return _c
}

func (_c *MockAWS_SSM_Call) RunAndReturn(run func(ctx context.Context, region string) (secrets.SSMClient, error)) *MockAWS_SSM_Call {
	_c.Call.Return(run)
	return _c
}
