// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"hexyn-aws/internal/awsx"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCredentialStore creates a new instance of MockCredentialStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialStore {
	mock := &MockCredentialStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCredentialStore is an autogenerated mock type for the CredentialStore type
type MockCredentialStore struct {
	mock.Mock
}

type MockCredentialStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialStore) EXPECT() *MockCredentialStore_Expecter {
	return &MockCredentialStore_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type MockCredentialStore
func (_mock *MockCredentialStore) Save(creds awsx.Credentials, arn string) error {
	ret := _mock.Called(creds, arn)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(awsx.Credentials, string) error); ok {
		r0 = returnFunc(creds, arn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCredentialStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockCredentialStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - creds awsx.Credentials
//   - arn string
func (_e *MockCredentialStore_Expecter) Save(creds interface{}, arn interface{}) *MockCredentialStore_Save_Call {
	return &MockCredentialStore_Save_Call{Call: _e.mock.On("Save", creds, arn)}
}

func (_c *MockCredentialStore_Save_Call) Run(run func(creds awsx.Credentials, arn string)) *MockCredentialStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 awsx.Credentials
		if args[0] != nil {
			arg0 = args[0].(awsx.Credentials)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCredentialStore_Save_Call) Return(err error) *MockCredentialStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCredentialStore_Save_Call) RunAndReturn(run func(creds awsx.Credentials, arn string) error) *MockCredentialStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRegion provides a mock function for the type MockCredentialStore
func (_mock *MockCredentialStore) UpdateRegion(region string) error {
	ret := _mock.Called(region)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRegion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(region)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCredentialStore_UpdateRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRegion'
type MockCredentialStore_UpdateRegion_Call struct {
	*mock.Call
}

// UpdateRegion is a helper method to define mock.On call
//   - region string
func (_e *MockCredentialStore_Expecter) UpdateRegion(region interface{}) *MockCredentialStore_UpdateRegion_Call {
	return &MockCredentialStore_UpdateRegion_Call{Call: _e.mock.On("UpdateRegion", region)}
}

func (_c *MockCredentialStore_UpdateRegion_Call) Run(run func(region string)) *MockCredentialStore_UpdateRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCredentialStore_UpdateRegion_Call) Return(err error) *MockCredentialStore_UpdateRegion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCredentialStore_UpdateRegion_Call) RunAndReturn(run func(region string) error) *MockCredentialStore_UpdateRegion_Call {
	_c.Call.Return(run)
	return _c
}
