// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"hexyn-aws/internal/awsx"

	mock "github.com/stretchr/testify/mock"
)

// NewMockECSClient creates a new instance of MockECSClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockECSClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockECSClient {
	mock := &MockECSClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockECSClient is an autogenerated mock type for the ECSClient type
type MockECSClient struct {
	mock.Mock
}

type MockECSClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockECSClient) EXPECT() *MockECSClient_Expecter {
	return &MockECSClient_Expecter{mock: &_m.Mock}
}

// GetTaskSecrets provides a mock function for the type MockECSClient
func (_mock *MockECSClient) GetTaskSecrets(ctx context.Context, cluster string, service string) ([]awsx.TaskSecret, []byte, error) {
	ret := _mock.Called(ctx, cluster, service)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskSecrets")
	}

	var r0 []awsx.TaskSecret
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]awsx.TaskSecret, []byte, error)); ok {
		return returnFunc(ctx, cluster, service)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []awsx.TaskSecret); ok {
		r0 = returnFunc(ctx, cluster, service)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]awsx.TaskSecret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) []byte); ok {
		r1 = returnFunc(ctx, cluster, service)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, cluster, service)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockECSClient_GetTaskSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskSecrets'
type MockECSClient_GetTaskSecrets_Call struct {
	*mock.Call
}

// GetTaskSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - cluster string
//   - service string
func (_e *MockECSClient_Expecter) GetTaskSecrets(ctx interface{}, cluster interface{}, service interface{}) *MockECSClient_GetTaskSecrets_Call {
	return &MockECSClient_GetTaskSecrets_Call{Call: _e.mock.On("GetTaskSecrets", ctx, cluster, service)}
}

func (_c *MockECSClient_GetTaskSecrets_Call) Run(run func(ctx context.Context, cluster string, service string)) *MockECSClient_GetTaskSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockECSClient_GetTaskSecrets_Call) Return(taskSecrets []awsx.TaskSecret, bytes []byte, err error) *MockECSClient_GetTaskSecrets_Call {
	_c.Call.Return(taskSecrets, bytes, err)
	return _c
}

func (_c *MockECSClient_GetTaskSecrets_Call) RunAndReturn(run func(ctx context.Context, cluster string, service string) ([]awsx.TaskSecret, []byte, error)) *MockECSClient_GetTaskSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// ListClusters provides a mock function for the type MockECSClient
func (_mock *MockECSClient) ListClusters(ctx context.Context) ([]awsx.Cluster, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListClusters")
	}

	var r0 []awsx.Cluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]awsx.Cluster, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []awsx.Cluster); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]awsx.Cluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockECSClient_ListClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClusters'
type MockECSClient_ListClusters_Call struct {
	*mock.Call
}

// ListClusters is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockECSClient_Expecter) ListClusters(ctx interface{}) *MockECSClient_ListClusters_Call {
	return &MockECSClient_ListClusters_Call{Call: _e.mock.On("ListClusters", ctx)}
}

func (_c *MockECSClient_ListClusters_Call) Run(run func(ctx context.Context)) *MockECSClient_ListClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockECSClient_ListClusters_Call) Return(clusters []awsx.Cluster, err error) *MockECSClient_ListClusters_Call {
	_c.Call.Return(clusters, err)
	return _c
}

func (_c *MockECSClient_ListClusters_Call) RunAndReturn(run func(ctx context.Context) ([]awsx.Cluster, error)) *MockECSClient_ListClusters_Call {
	_c.Call.Return(run)
	return _c
}

// ListServices provides a mock function for the type MockECSClient
func (_mock *MockECSClient) ListServices(ctx context.Context, cluster string) ([]awsx.Service, error) {
	ret := _mock.Called(ctx, cluster)

	if len(ret) == 0 {
		panic("no return value specified for ListServices")
	}

	var r0 []awsx.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]awsx.Service, error)); ok {
		return returnFunc(ctx, cluster)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []awsx.Service); ok {
		r0 = returnFunc(ctx, cluster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]awsx.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cluster)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockECSClient_ListServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServices'
type MockECSClient_ListServices_Call struct {
	*mock.Call
}

// ListServices is a helper method to define mock.On call
//   - ctx context.Context
//   - cluster string
func (_e *MockECSClient_Expecter) ListServices(ctx interface{}, cluster interface{}) *MockECSClient_ListServices_Call {
	return &MockECSClient_ListServices_Call{Call: _e.mock.On("ListServices", ctx, cluster)}
}

func (_c *MockECSClient_ListServices_Call) Run(run func(ctx context.Context, cluster string)) *MockECSClient_ListServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockECSClient_ListServices_Call) Return(services []awsx.Service, err error) *MockECSClient_ListServices_Call {
	_c.Call.Return(services, err)
	return _c
}

func (_c *MockECSClient_ListServices_Call) RunAndReturn(run func(ctx context.Context, cluster string) ([]awsx.Service, error)) *MockECSClient_ListServices_Call {
	_c.Call.Return(run)
	return _c
}
