// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"hexyn-aws/internal/awsx"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEnvFiles creates a new instance of MockEnvFiles. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnvFiles(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnvFiles {
	mock := &MockEnvFiles{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEnvFiles is an autogenerated mock type for the EnvFiles type
type MockEnvFiles struct {
	mock.Mock
}

type MockEnvFiles_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnvFiles) EXPECT() *MockEnvFiles_Expecter {
	return &MockEnvFiles_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockEnvFiles
func (_mock *MockEnvFiles) Parse(path string) ([]awsx.Parameter, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 []awsx.Parameter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]awsx.Parameter, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []awsx.Parameter); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]awsx.Parameter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEnvFiles_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockEnvFiles_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - path string
func (_e *MockEnvFiles_Expecter) Parse(path interface{}) *MockEnvFiles_Parse_Call {
	return &MockEnvFiles_Parse_Call{Call: _e.mock.On("Parse", path)}
}

func (_c *MockEnvFiles_Parse_Call) Run(run func(path string)) *MockEnvFiles_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEnvFiles_Parse_Call) Return(parameters []awsx.Parameter, err error) *MockEnvFiles_Parse_Call {
	_c.Call.Return(parameters, err)
	return _c
}

func (_c *MockEnvFiles_Parse_Call) RunAndReturn(run func(path string) ([]awsx.Parameter, error)) *MockEnvFiles_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type MockEnvFiles
func (_mock *MockEnvFiles) Write(dir string, name string, params []awsx.Parameter) error {
	ret := _mock.Called(dir, name, params)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, []awsx.Parameter) error); ok {
		r0 = returnFunc(dir, name, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEnvFiles_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockEnvFiles_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - dir string
//   - name string
//   - params []awsx.Parameter
func (_e *MockEnvFiles_Expecter) Write(dir interface{}, name interface{}, params interface{}) *MockEnvFiles_Write_Call {
	return &MockEnvFiles_Write_Call{Call: _e.mock.On("Write", dir, name, params)}
}

func (_c *MockEnvFiles_Write_Call) Run(run func(dir string, name string, params []awsx.Parameter)) *MockEnvFiles_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []awsx.Parameter
		if args[2] != nil {
			arg2 = args[2].([]awsx.Parameter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEnvFiles_Write_Call) Return(err error) *MockEnvFiles_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEnvFiles_Write_Call) RunAndReturn(run func(dir string, name string, params []awsx.Parameter) error) *MockEnvFiles_Write_Call {
	_c.Call.Return(run)
	return _c
}

// WriteRaw provides a mock function for the type MockEnvFiles
func (_mock *MockEnvFiles) WriteRaw(dir string, name string, data []byte) error {
	ret := _mock.Called(dir, name, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteRaw")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, []byte) error); ok {
		r0 = returnFunc(dir, name, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEnvFiles_WriteRaw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteRaw'
type MockEnvFiles_WriteRaw_Call struct {
	*mock.Call
}

// WriteRaw is a helper method to define mock.On call
//   - dir string
//   - name string
//   - data []byte
func (_e *MockEnvFiles_Expecter) WriteRaw(dir interface{}, name interface{}, data interface{}) *MockEnvFiles_WriteRaw_Call {
	return &MockEnvFiles_WriteRaw_Call{Call: _e.mock.On("WriteRaw", dir, name, data)}
}

func (_c *MockEnvFiles_WriteRaw_Call) Run(run func(dir string, name string, data []byte)) *MockEnvFiles_WriteRaw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEnvFiles_WriteRaw_Call) Return(err error) *MockEnvFiles_WriteRaw_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEnvFiles_WriteRaw_Call) RunAndReturn(run func(dir string, name string, data []byte) error) *MockEnvFiles_WriteRaw_Call {
	_c.Call.Return(run)
	return _c
}
