// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"hexyn-aws/internal/awsx"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionClient creates a new instance of MockSessionClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionClient {
	mock := &MockSessionClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionClient is an autogenerated mock type for the SessionClient type
type MockSessionClient struct {
	mock.Mock
}

type MockSessionClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionClient) EXPECT() *MockSessionClient_Expecter {
	return &MockSessionClient_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type MockSessionClient
func (_mock *MockSessionClient) Check(ctx context.Context) (awsx.Session, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 awsx.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (awsx.Session, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) awsx.Session); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(awsx.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionClient_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockSessionClient_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSessionClient_Expecter) Check(ctx interface{}) *MockSessionClient_Check_Call {
	return &MockSessionClient_Check_Call{Call: _e.mock.On("Check", ctx)}
}

func (_c *MockSessionClient_Check_Call) Run(run func(ctx context.Context)) *MockSessionClient_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionClient_Check_Call) Return(session awsx.Session, err error) *MockSessionClient_Check_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionClient_Check_Call) RunAndReturn(run func(ctx context.Context) (awsx.Session, error)) *MockSessionClient_Check_Call {
	_c.Call.Return(run)
	return _c
}

// ListEnabledRegions provides a mock function for the type MockSessionClient
func (_mock *MockSessionClient) ListEnabledRegions(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListEnabledRegions")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionClient_ListEnabledRegions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEnabledRegions'
type MockSessionClient_ListEnabledRegions_Call struct {
	*mock.Call
}

// ListEnabledRegions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSessionClient_Expecter) ListEnabledRegions(ctx interface{}) *MockSessionClient_ListEnabledRegions_Call {
	return &MockSessionClient_ListEnabledRegions_Call{Call: _e.mock.On("ListEnabledRegions", ctx)}
}

func (_c *MockSessionClient_ListEnabledRegions_Call) Run(run func(ctx context.Context)) *MockSessionClient_ListEnabledRegions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionClient_ListEnabledRegions_Call) Return(strings []string, err error) *MockSessionClient_ListEnabledRegions_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockSessionClient_ListEnabledRegions_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockSessionClient_ListEnabledRegions_Call {
	_c.Call.Return(run)
	return _c
}
