// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"hexyn-aws/internal/awsx"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSSMClient creates a new instance of MockSSMClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSSMClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSSMClient {
	mock := &MockSSMClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSSMClient is an autogenerated mock type for the SSMClient type
type MockSSMClient struct {
	mock.Mock
}

type MockSSMClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSSMClient) EXPECT() *MockSSMClient_Expecter {
	return &MockSSMClient_Expecter{mock: &_m.Mock}
}

// GetByNames provides a mock function for the type MockSSMClient
func (_mock *MockSSMClient) GetByNames(ctx context.Context, nameMap map[string]string) ([]awsx.Parameter, error) {
	ret := _mock.Called(ctx, nameMap)

	if len(ret) == 0 {
		panic("no return value specified for GetByNames")
	}

	var r0 []awsx.Parameter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string) ([]awsx.Parameter, error)); ok {
		return returnFunc(ctx, nameMap)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string) []awsx.Parameter); ok {
		r0 = returnFunc(ctx, nameMap)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]awsx.Parameter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]string) error); ok {
		r1 = returnFunc(ctx, nameMap)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSSMClient_GetByNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByNames'
type MockSSMClient_GetByNames_Call struct {
	*mock.Call
}

// GetByNames is a helper method to define mock.On call
//   - ctx context.Context
//   - nameMap map[string]string
func (_e *MockSSMClient_Expecter) GetByNames(ctx interface{}, nameMap interface{}) *MockSSMClient_GetByNames_Call {
	return &MockSSMClient_GetByNames_Call{Call: _e.mock.On("GetByNames", ctx, nameMap)}
}

func (_c *MockSSMClient_GetByNames_Call) Run(run func(ctx context.Context, nameMap map[string]string)) *MockSSMClient_GetByNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSSMClient_GetByNames_Call) Return(parameters []awsx.Parameter, err error) *MockSSMClient_GetByNames_Call {
	_c.Call.Return(parameters, err)
	return _c
}

func (_c *MockSSMClient_GetByNames_Call) RunAndReturn(run func(ctx context.Context, nameMap map[string]string) ([]awsx.Parameter, error)) *MockSSMClient_GetByNames_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPath provides a mock function for the type MockSSMClient
func (_mock *MockSSMClient) GetByPath(ctx context.Context, dest awsx.ParamPath) ([]awsx.Parameter, error) {
	ret := _mock.Called(ctx, dest)

	if len(ret) == 0 {
		panic("no return value specified for GetByPath")
	}

	var r0 []awsx.Parameter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, awsx.ParamPath) ([]awsx.Parameter, error)); ok {
		return returnFunc(ctx, dest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, awsx.ParamPath) []awsx.Parameter); ok {
		r0 = returnFunc(ctx, dest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]awsx.Parameter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, awsx.ParamPath) error); ok {
		r1 = returnFunc(ctx, dest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSSMClient_GetByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPath'
type MockSSMClient_GetByPath_Call struct {
	*mock.Call
}

// GetByPath is a helper method to define mock.On call
//   - ctx context.Context
//   - dest awsx.ParamPath
func (_e *MockSSMClient_Expecter) GetByPath(ctx interface{}, dest interface{}) *MockSSMClient_GetByPath_Call {
	return &MockSSMClient_GetByPath_Call{Call: _e.mock.On("GetByPath", ctx, dest)}
}

func (_c *MockSSMClient_GetByPath_Call) Run(run func(ctx context.Context, dest awsx.ParamPath)) *MockSSMClient_GetByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 awsx.ParamPath
		if args[1] != nil {
			arg1 = args[1].(awsx.ParamPath)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSSMClient_GetByPath_Call) Return(parameters []awsx.Parameter, err error) *MockSSMClient_GetByPath_Call {
	_c.Call.Return(parameters, err)
	return _c
}

func (_c *MockSSMClient_GetByPath_Call) RunAndReturn(run func(ctx context.Context, dest awsx.ParamPath) ([]awsx.Parameter, error)) *MockSSMClient_GetByPath_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockSSMClient
func (_mock *MockSSMClient) Put(ctx context.Context, dest awsx.ParamPath, params []awsx.Parameter) (int, []error) {
	ret := _mock.Called(ctx, dest, params)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 int
	var r1 []error
	if returnFunc, ok := ret.Get(0).(func(context.Context, awsx.ParamPath, []awsx.Parameter) (int, []error)); ok {
		return returnFunc(ctx, dest, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, awsx.ParamPath, []awsx.Parameter) int); ok {
		r0 = returnFunc(ctx, dest, params)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, awsx.ParamPath, []awsx.Parameter) []error); ok {
		r1 = returnFunc(ctx, dest, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]error)
		}
	}
	return r0, r1
}

// MockSSMClient_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockSSMClient_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - dest awsx.ParamPath
//   - params []awsx.Parameter
func (_e *MockSSMClient_Expecter) Put(ctx interface{}, dest interface{}, params interface{}) *MockSSMClient_Put_Call {
	return &MockSSMClient_Put_Call{Call: _e.mock.On("Put", ctx, dest, params)}
}

func (_c *MockSSMClient_Put_Call) Run(run func(ctx context.Context, dest awsx.ParamPath, params []awsx.Parameter)) *MockSSMClient_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 awsx.ParamPath
		if args[1] != nil {
			arg1 = args[1].(awsx.ParamPath)
		}
		var arg2 []awsx.Parameter
		if args[2] != nil {
			arg2 = args[2].([]awsx.Parameter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSSMClient_Put_Call) Return(n int, errs []error) *MockSSMClient_Put_Call {
	_c.Call.Return(n, errs)
	return _c
}

func (_c *MockSSMClient_Put_Call) RunAndReturn(run func(ctx context.Context, dest awsx.ParamPath, params []awsx.Parameter) (int, []error)) *MockSSMClient_Put_Call {
	_c.Call.Return(run)
	return _c
}
